In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]], int)
print(arr)
print(arr.shape)
new_arr = np.expand_dims(arr, axis=2)
print(new_arr)
print(new_arr.shape)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
(3, 4)
[[[1]
  [2]
  [3]
  [4]]

 [[2]
  [3]
  [4]
  [5]]

 [[3]
  [4]
  [5]
  [6]]]
(3, 4, 1)


In [3]:
arr = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]], int)
print(arr.shape)
# n_arr = arr[np.newaxis]
# n_arr = arr[:,np.newaxis]
n_arr = arr[np.newaxis, :, np.newaxis]
# n_arr = arr[:, :, np.newaxis]
# n_arr = arr[..., np.newaxis]

n_arr.shape

(3, 4)


(1, 3, 1, 4)

In [4]:
# удаление осей
n_arr = np.squeeze(n_arr)
n_arr.shape

(3, 4)

In [5]:
# объединение массивов
ls = [[1, 2, 3], [2, 3, 4], [3, 4, 5]]

arr1 = np.array(ls)
arr2 = np.array([[4, 5, 6], [5, 6, 7], [6, 7, 8]])
arr3 = np.array([[7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12]])
arr3.shape = 4, 3
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr3)
# new_arr = np.hstack([arr1, arr2, arr3])
# new_arr = np.vstack([arr1, arr2, arr3])
print(new_arr)

(3, 3)
(3, 3)
(4, 3)
[[ 7  8  9]
 [10  8  9]
 [10 11  9]
 [10 11 12]]
[[[1]
  [2]
  [3]
  [4]]

 [[2]
  [3]
  [4]
  [5]]

 [[3]
  [4]
  [5]
  [6]]]


In [6]:
new_arr = np.concatenate([arr1, arr2, arr3], axis=0)
print(new_arr)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [10  8  9]
 [10 11  9]
 [10 11 12]]


In [7]:
arr = [['x_1', 'y_1'],
       ['x_2', 'y_2'],
       ['x_3', 'y_3'],
       ['x_4', 'y_4']]
arr1l, arr2l = np.array_split(arr, 2, axis=0)
arr_l = np.array_split(arr, 4, axis=1)
# print('1', arr1l)
# print('2', arr2l)
print(arr_l)

[array([['x_1'],
       ['x_2'],
       ['x_3'],
       ['x_4']], dtype='<U3'), array([['y_1'],
       ['y_2'],
       ['y_3'],
       ['y_4']], dtype='<U3'), array([], shape=(4, 0), dtype='<U3'), array([], shape=(4, 0), dtype='<U3')]


In [8]:
data = np.empty([1000, 28, 28])
arr1 = np.empty([50, 28, 28])
arr11 = np.empty([50, 28, 20])
arr3 = np.empty([28, 28])
print('data', data.shape)
print(data.ndim)
print('arr1', arr1.shape)
print('arr3', arr3.shape)
# new_arr = np.append(data, arr1)

new_arr = np.append(data, arr1, axis=0)
new_arr = np.append(arr1, arr11, axis=2)
# new_arr = np.append(data, arr11, axis=0)
new_arr = np.append(data, arr3[np.newaxis], axis=0)

new_arr.shape

data (1000, 28, 28)
3
arr1 (50, 28, 28)
arr3 (28, 28)


(1001, 28, 28)

In [9]:
new_data = np.delete(new_arr, 1000, axis=0)
print(new_data.shape)

(1000, 28, 28)


In [10]:
%%time
data = np.empty([1000, 28, 28])
for i in range(1000):
    img = np.random.randint(0, 256, (28, 28))
    data = np.append(data, img[np.newaxis], axis=0)
print(data.shape)


(2000, 28, 28)
CPU times: total: 6.89 s
Wall time: 7.99 s


In [11]:
%%time
data = np.empty([1000, 28, 28])
data.resize([2000, 28, 28], refcheck=False)
for i in range(1000):
    img = np.random.randint(0, 256, (28, 28))
    data[1000 + i] = img
print(data.shape)


(2000, 28, 28)
CPU times: total: 172 ms
Wall time: 172 ms


In [12]:
# Индексация
arr = np.arange(18).reshape((3, 3, 2))
print(arr.shape, '\n\n', arr)
# print(arr[0])
# print(arr[2, 1])
print(arr[2, 2, 0])
arr[1, 0] = 100
arr

(3, 3, 2) 

 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
16


array([[[  0,   1],
        [  2,   3],
        [  4,   5]],

       [[100, 100],
        [  8,   9],
        [ 10,  11]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]]])

In [23]:
arr = np.arange(4 * 3 * 2).reshape(4, 3, 2)
print(arr.shape, '\n\n', arr)
# arr[0:2, 2]
# arr[:, 1]
# arr[1:, :, 1]
arr[::2, 2]

(4, 3, 2) 

 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


array([[ 4,  5],
       [16, 17]])

In [19]:
# arr[:, 1]= 100
# arr[1] = 50
# arr

array([[[  0,   1],
        [100, 100],
        [  4,   5]],

       [[ 50,  50],
        [ 50,  50],
        [ 50,  50]],

       [[ 12,  13],
        [100, 100],
        [ 16,  17]],

       [[ 18,  19],
        [100, 100],
        [ 22,  23]]])

In [41]:
# arr[[1, 3, 1, 2, 0],1:2]
# arr[np.array([1, 3, 2, 1])]
arr = np.arange(2 * 2).reshape(2,2)
print(arr)
new = arr[[0,1]]
new[0] = 55
print(new)
print(arr)

[[0 1]
 [2 3]]
[[55 55]
 [ 2  3]]
[[0 1]
 [2 3]]


In [44]:
arr = np.arange(6).reshape([3, 2])
print(arr)
index = np.array([[0,0,1], [1,0,2]])
arr[index]

[[0 1]
 [2 3]
 [4 5]]


array([[[0, 1],
        [0, 1],
        [2, 3]],

       [[2, 3],
        [0, 1],
        [4, 5]]])