In [18]:
import numpy as np

In [19]:
arr1 = np.arange(6).reshape(3, 2)
print(arr1)
arr2 = np.arange(10, 16).reshape(3, 2)
print(arr2)
arr1 * 5
arr1 + arr2
print(arr1.shape)
print(arr2.shape)

[[0 1]
 [2 3]
 [4 5]]
[[10 11]
 [12 13]
 [14 15]]
(3, 2)
(3, 2)


In [20]:
arr1 = np.arange(1, 13).reshape(4, 3)
print(arr1)
arr2 = np.arange(100, 103)
# arr2 = arr2[np.newaxis]
print(arr2)
arr1 + arr2


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[100 101 102]


array([[101, 103, 105],
       [104, 106, 108],
       [107, 109, 111],
       [110, 112, 114]])

In [21]:
# shape(4,3,5)  и число 55 всегда согасованы
# shape(4,3,5)  и масив [1] shape(1,) с одним элементом всегда согасованы
# shape(4,3,5) и  shape(5,) или сами или автоматически (1,1,5)
# shape(4,3,5) и  shape(4,) -> expand_dims(arr, axis=[1, 2]) (4, 1, 1)
# shape(4,3,5) и  shape(4, 5) -> arr[:,np.newaxis]  ( 4, 1, 5)

In [22]:
# arr = np.array([3])
# arr = np.array([5, 7, 1])
# arr = np.arange(3)
# arr.shape = 3,1
arr = np.arange(4 * 3 * 2).reshape(4, 3, 2)
arr1 = np.arange(4 * 2).reshape(4, 2)
arr1.shape = 4, 1, 2
# arr1 = np.arange(1, 13).reshape(4,3)
print(arr1)
print(arr)
print(arr + arr1)

[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[ 0  2]
  [ 2  4]
  [ 4  6]]

 [[ 8 10]
  [10 12]
  [12 14]]

 [[16 18]
  [18 20]
  [20 22]]

 [[24 26]
  [26 28]
  [28 30]]]


In [23]:
arr = np.arange(5 * 3 * 2).reshape(5, 3, 2)
arr1 = np.arange(5, 10)
print(arr.shape)
print(arr1.shape)
arr1.shape = 5, 1, 1
print(arr1.shape)
arr - arr1

(5, 3, 2)
(5,)
(5, 1, 1)


array([[[-5, -4],
        [-3, -2],
        [-1,  0]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[10, 11],
        [12, 13],
        [14, 15]],

       [[15, 16],
        [17, 18],
        [19, 20]]])

In [24]:
arr = np.arange(2, 20).reshape(3, 3, 2)
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.sum())



2
19
10.5
189


In [25]:
np.abs(np.array([[-1, 2, -3], [-4, -6, 3]]))
np.max(arr)
np.log(arr)
np.exp(arr)
np.log(np.exp(arr))
np.sin(arr)
np.cos(arr)
np.arctan(arr)

array([[[1.10714872, 1.24904577],
        [1.32581766, 1.37340077],
        [1.40564765, 1.42889927]],

       [[1.44644133, 1.46013911],
        [1.47112767, 1.48013644],
        [1.48765509, 1.49402444]],

       [[1.49948886, 1.50422816],
        [1.50837752, 1.5120405 ],
        [1.51529782, 1.51821327]]])

In [26]:
arr = np.arange(2, 20).reshape(3, 3, 2)
print(arr)
# print(np.sum(arr, axis=0))
# print(np.mean(arr, axis=1))
print(np.max(arr, axis=2))

[[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]]

 [[14 15]
  [16 17]
  [18 19]]]
[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]


In [40]:
arr = np.arange(10).reshape(5, 2)
# print(arr)
# arr = np.arange(18).reshape(3, 3, 2)
# arr.shape = -1, 2
# arr = np.arange(3 * 4 * 4 * 3).reshape(3, 4, 4, 3)
# arr.shape = [3, 4 * 4, 3]
# arr.shape = -1, 3

print(arr)
print(np.mean(arr, axis=(0, 1)))
# print(np.mean(arr,axis=1))
# print(np.mean(arr))
# np.mean(arr,axis=( 0, 1))



[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
4.5


In [45]:
print(np.median(arr))
print(np.var(arr))
np.std(arr)

4.5
8.25


np.float64(2.8722813232690143)

In [54]:
np.random.rand()
np.random.rand(4)
np.random.rand(3, 2)

array([[0.52315536, 0.5876991 ],
       [0.96441284, 0.18452313],
       [0.28893692, 0.33835874]])

In [68]:
print(np.random.randn())
print(np.random.randn(6))
print(np.random.randn(3, 2))

0.14981694412817503
[-2.79271334 -0.12650059 -0.65956174  0.63065042 -0.52629541 -2.05769773]
[[-1.15525038 -0.66151414]
 [ 0.51449452  0.31568507]
 [ 0.65646413  0.36535802]]


In [84]:
np.random.normal(5, 10)
np.random.normal(5, 10, 100)
np.random.normal(5, 10, [4, 2])

array([[ -4.73339402,   7.53704835],
       [ 13.70769423,  13.36294274],
       [  3.21733374,  17.43554048],
       [ -0.93214089, -21.83330777]])

In [90]:
np.random.randint(5)
np.random.randint(4, 10)
np.random.randint(4, 10, size=(4, 2))

array([[5, 6],
       [5, 7],
       [4, 4],
       [9, 9]], dtype=int32)

In [91]:
np.random.choice([1, 2, 3, 4, 5], 10)

array([4, 4, 1, 1, 2, 2, 4, 1, 4, 5])

In [99]:
arr = np.arange(10).reshape(5, 2)
print(arr)
np.random.seed(0)
np.random.shuffle(arr)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[4 5]
 [0 1]
 [2 3]
 [6 7]
 [8 9]]
