In [2]:
from typing import Sequence

import torch
import torch.nn as nn
from torch.nn import Sequential

In [3]:
model = nn.Sequential(
    nn.Linear(784, 128),
    nn.ReLU(),
    nn.Linear(128, 10)
)


In [4]:
input = torch.rand([16, 784], dtype=torch.float32)
# input
output = model(input)
output.shape
# output

torch.Size([16, 10])

In [5]:
model.state_dict()
model.state_dict()['2.weight']
model.state_dict()['2.bias']

tensor([ 0.0782,  0.0814, -0.0271,  0.0614,  0.0792,  0.0546,  0.0094,  0.0556,
        -0.0378,  0.0096])

In [6]:
for parameter in model.parameters():
    print(parameter)
    print(parameter.shape)

Parameter containing:
tensor([[-0.0091, -0.0290,  0.0104,  ...,  0.0068,  0.0315,  0.0254],
        [ 0.0122, -0.0200, -0.0299,  ...,  0.0201, -0.0065, -0.0138],
        [ 0.0314,  0.0355,  0.0246,  ...,  0.0357, -0.0085, -0.0041],
        ...,
        [ 0.0055,  0.0324,  0.0273,  ...,  0.0087,  0.0248,  0.0062],
        [-0.0227,  0.0155,  0.0197,  ..., -0.0080, -0.0006,  0.0054],
        [ 0.0341,  0.0281, -0.0016,  ...,  0.0090, -0.0120, -0.0120]],
       requires_grad=True)
torch.Size([128, 784])
Parameter containing:
tensor([ 0.0312,  0.0152, -0.0327,  0.0189,  0.0247, -0.0132,  0.0185, -0.0172,
        -0.0141,  0.0126,  0.0117,  0.0150,  0.0216, -0.0173,  0.0245,  0.0248,
         0.0013, -0.0346, -0.0145, -0.0237, -0.0136, -0.0091, -0.0252, -0.0158,
         0.0220,  0.0197,  0.0087, -0.0134,  0.0056,  0.0194,  0.0342,  0.0029,
        -0.0261, -0.0272, -0.0150,  0.0052, -0.0005,  0.0095,  0.0299,  0.0186,
        -0.0075, -0.0175,  0.0074,  0.0171, -0.0208,  0.0345, -0.0296, -

In [7]:
# model.train()
# model.eval()

In [8]:
model = nn.Sequential()
model.add_module('layer_1', nn.Linear(784, 128))
model.add_module('relu', nn.ReLU())
model.add_module('layer_2', nn.Linear(128, 10))
model
model.layer_1
model.relu

ReLU()

In [9]:
input = torch.rand([16, 784], dtype=torch.float32)
output = model(input)
output.shape

torch.Size([16, 10])

In [10]:
model.state_dict()


OrderedDict([('layer_1.weight',
              tensor([[ 0.0278,  0.0205, -0.0177,  ..., -0.0184,  0.0326,  0.0008],
                      [-0.0334, -0.0189,  0.0013,  ...,  0.0319,  0.0245,  0.0139],
                      [-0.0048,  0.0122, -0.0189,  ..., -0.0209, -0.0065, -0.0275],
                      ...,
                      [-0.0307, -0.0152, -0.0198,  ..., -0.0099, -0.0040,  0.0336],
                      [-0.0103, -0.0352, -0.0103,  ...,  0.0092, -0.0075, -0.0353],
                      [ 0.0113,  0.0260, -0.0297,  ...,  0.0183, -0.0123, -0.0203]])),
             ('layer_1.bias',
              tensor([ 2.2848e-03, -2.0539e-02,  9.9707e-03, -2.1482e-02,  7.6330e-03,
                       1.6977e-02, -7.5235e-03,  3.4775e-02,  2.1839e-02,  1.4162e-02,
                      -9.7380e-03, -1.7371e-02,  3.2380e-02,  2.7543e-02, -2.2110e-02,
                       1.1452e-02, -1.7045e-03,  1.7613e-02,  2.3869e-02,  1.1348e-02,
                      -2.7147e-02,  1.7728e-02,  1.7650e

In [11]:
class MyModel(nn.Module):
    def __init__(self, input, output):
        super().__init__()
        self.layer_1 = nn.Linear(input, 128)
        self.layer_2 = nn.Linear(128, output)
        self.act = nn.ReLU()

    def forward(self, x):
        x = self.layer_1(x)
        x = self.act(x)
        out = self.layer_2(x)
        return out


model = MyModel(784, 10)

In [12]:
input = torch.rand([16, 784], dtype=torch.float32)
output = model(input)
# output.shape
# model.state_dict()

In [13]:
class MyModel(nn.Module):
    def __init__(self, input, output):
        super().__init__()
        self.layer_1 = nn.Linear(input, 128)
        self.layer_2 = nn.Linear(128, output)
        self.act = nn.ReLU()

    def forward(self, x, y):
        x = self.layer_1(x)
        x = self.act(x + y)
        out = self.layer_2(x)
        return out, x


model = MyModel(784, 10)

In [14]:
x = torch.rand([16, 784], dtype=torch.float32)
y = torch.rand([16, 128], dtype=torch.float32)
out = model(x, y)
len(out)
print(out[0].shape)
print(out[1].shape)
# model.state_dict()

torch.Size([16, 10])
torch.Size([16, 128])


In [15]:
class MyModel(nn.Module):
    def __init__(self, input, output, hidden_size=2048):
        super().__init__()
        self.layers = nn.ModuleList()
        for i in range(10):
            self.layers.add_module(f'layer_{i})', nn.Linear(input, hidden_size))
            self.layers.add_module(f'act_{i})', nn.ReLU())
            input = hidden_size
            hidden_size = int(hidden_size / 2)
        self.layers.add_module(f'output_{i})', nn.Linear(input, output))

    def forward(self, x):
        output = []
        for i, layer in enumerate(self.layers):
            x = layer(x)
            if i != 0 and i % 2 == 0 and i % 4 != 0:
                output.append(x)
        output.append(x)
        return output


In [16]:
model = MyModel(784, 2)
input = torch.rand([16, 784], dtype=torch.float32)
output = model(input)
print(len(output))
print(output[0].shape)
print(output[1].shape)
print(output[2].shape)
print(output[3].shape)
print(output[4].shape)
print(output[5].shape)

6
torch.Size([16, 1024])
torch.Size([16, 256])
torch.Size([16, 64])
torch.Size([16, 16])
torch.Size([16, 4])
torch.Size([16, 2])


In [6]:
class MyModel(nn.Module):
    def __init__(self, input, output, hidden_size=2048, choice='relu'):
        super().__init__()
        self.activation = nn.ModuleDict(
        {
            'relu': nn.ReLU(),
            'lrelu': nn.LeakyReLU(),
        }
        )
        self.layers = nn.ModuleList()
        for i in range(10):
            self.layers.add_module(f'layer_{i})', nn.Linear(input, hidden_size))
            self.layers.add_module(f'act_{i})', self.activation[choice])
            input = hidden_size
            hidden_size = int(hidden_size / 2)
        self.layers.add_module(f'output_{i})', nn.Linear(input, output))

    def forward(self, x):
        output = []
        for i, layer in enumerate(self.layers):
            x = layer(x)
            if i != 0 and i % 2 == 0 and i % 4 != 0:
                output.append(x)
        output.append(x)
        return output


In [7]:
model = MyModel(784, 2, choice='lrelu')
model

MyModel(
  (activation): ModuleDict(
    (relu): ReLU()
    (lrelu): LeakyReLU(negative_slope=0.01)
  )
  (layers): ModuleList(
    (0): Linear(in_features=784, out_features=2048, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=2048, out_features=1024, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=1024, out_features=512, bias=True)
    (5): LeakyReLU(negative_slope=0.01)
    (6): Linear(in_features=512, out_features=256, bias=True)
    (7): LeakyReLU(negative_slope=0.01)
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): LeakyReLU(negative_slope=0.01)
    (10): Linear(in_features=128, out_features=64, bias=True)
    (11): LeakyReLU(negative_slope=0.01)
    (12): Linear(in_features=64, out_features=32, bias=True)
    (13): LeakyReLU(negative_slope=0.01)
    (14): Linear(in_features=32, out_features=16, bias=True)
    (15): LeakyReLU(negative_slope=0.01)
    (16): Linear(in_features=16, out_features=8, bi

In [3]:
arr = torch.tensor([[0, 0], [1, 1], [2, 2], [3, 0], [4, 1], [5, 2], [6, 1]], dtype=torch.float32)
targ = arr.reshape(-1).to(torch.int32)
targ
tch = torch.eye(7)[targ]
tch

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0.]])