In [3]:
import numpy as np


In [4]:
arr = np.array([1, 2, 3, 8], dtype='float32')
print(arr)
arr[3]

[1. 2. 3. 8.]


np.float32(8.0)

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='int32')
print(arr[1][1])

print(arr[2, 0])
print(arr)
print(arr[-1, -2])


5
7
[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [6]:
arr.shape = 3, 3
arr1 = arr.reshape([1, 9])
print(arr1.shape)
arr[2, 2] = 100
print(arr)
print(arr1)

(1, 9)
[[  1   2   3]
 [  4   5   6]
 [  7   8 100]]
[[  1   2   3   4   5   6   7   8 100]]


In [25]:
arr = np.array([[1, 2], [3, 4]], dtype='int32')
print(arr.dtype)
print(arr.shape)
# arr.dtype = np.float32
# arr.dtype
print(arr)
arr.dtype = 'int8'
print(arr)
arr.shape


int32
(2, 2)
[[1 2]
 [3 4]]
[[1 0 0 0 2 0 0 0]
 [3 0 0 0 4 0 0 0]]


(2, 8)

In [8]:
np.empty([3, 4, 1])

array([[[1.07284626e-317],
        [6.66323560e-317],
        [            nan],
        [1.24636384e-316]],

       [[            nan],
        [7.65483869e-317],
        [7.65483869e-317],
        [            nan]],

       [[1.24636384e-316],
        [            nan],
        [6.66323560e-317],
        [1.07284626e-317]]])

In [9]:
arr = np.arange(1, 11).reshape(2, 5)


In [10]:
# np.ones([4, 5], dtype='int8')
# np.zeros([4, 5], dtype='int8')
# np.full([4, 5], 7, dtype='int8')
# np.full_like(arr, 7, dtype='int8')
# np.zeros_like(arr, dtype='int8')
np.ones_like(arr, dtype='int8')



array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [11]:
# матрицы
np.asmatrix([1, 2, 3, 4, 5, 6])
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='int8')
print(arr)
print(np.diag(arr))
np.diagflat(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]], dtype=int8)

In [29]:
npp = np.eye(4)
npp = np.eye(4, 5)
# npp.shape=1, 4, 4
print(npp)

npp.ndim

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


2

In [32]:
np.identity(5, int)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [34]:
# np.tri(7)
np.tri(5, 8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0.]])

In [37]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10], [9, 10, 11, 12]], dtype='int8')
print(arr)
np.tril(arr)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [ 9 10 11 12]]


array([[ 1,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 7,  8,  9,  0],
       [ 9, 10, 11, 12]], dtype=int8)

In [38]:
np.triu(arr)

array([[ 1,  2,  3,  4],
       [ 0,  5,  6,  7],
       [ 0,  0,  9, 10],
       [ 0,  0,  0, 12]], dtype=int8)

In [64]:
#shape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype='int8')
# arr.shape = (2, 2, 3)
arr.shape = 4, 3
arr.shape = 12
arr.shape = -1, 12
arr.shape = 12, -1
arr.shape = 4, -1
arr.shape = -1, 4
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
#reshape
arr1 = arr.reshape(4, 3)
print(arr1)
print(arr)
arr[0] = 20
print(arr1)
print(arr)

[[20 20 20]
 [20  5  6]
 [ 7  8  9]
 [10 11 12]]
[[20 20 20 20]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[20 20 20]
 [20  5  6]
 [ 7  8  9]
 [10 11 12]]
[[20 20 20 20]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [69]:
#resize
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype='int8')
print(arr.shape)
arr.resize(2, 6)
print(arr)

(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [80]:
arr.resize((2,8), refcheck=False)
arr.resize((7,2), refcheck=False)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 0  0]]


In [76]:
#ravel
arr2 = arr.ravel()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  0,  0,  0,  0,
        0,  0,  0], dtype=int8)

In [84]:
# копия представления
arr_v = arr.view()
print(arr_v)
arr_v.shape = (2,-1)
print(arr_v)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 0  0]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12  0  0]]


In [85]:
arr_c = arr.copy()
arr_c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [ 0,  0]], dtype=int8)