In [1]:
import numpy as np

In [2]:
# ==, !=, >, >=, <, <=

In [6]:
np.random.seed(42)
arr1 = np.random.randint(10, size=(4, 3))
print(arr1)
arr2 = arr1[[2, 1, 2, 0]]
print(arr2)

[[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]]
[[2 6 7]
 [4 6 9]
 [2 6 7]
 [6 3 7]]


In [4]:
arr1 == 7
print(arr1 > 4)
print(arr1[arr1 > 4])

[[ True False  True]
 [False  True  True]
 [False  True  True]
 [False False  True]]
[6 7 6 9 6 7 7]


In [7]:
arr1 == arr2
np.random.seed(42)
arr3 = np.random.randint(10, size=(2, 3, 2))
shape_3_2 = np.arange(2, 8).reshape(3, 2)


In [12]:
print(arr3)
# arr3 == [7, 3]
print(shape_3_2)
np.less(arr3, shape_3_2)


[[[6 3]
  [7 4]
  [6 9]]

 [[2 6]
  [7 4]
  [3 7]]]
[[2 3]
 [4 5]
 [6 7]]


array([[[False, False],
        [False,  True],
        [False, False]],

       [[False, False],
        [False,  True],
        [ True, False]]])

In [ ]:
# np.greater() -> >
#np.greater_equal() -> >=
# np.less() -> <
# np.less-equal() -> <=
# np.equal() -> ==
# np.not_equal() -> !=


In [25]:
# сравнение не согласованных массивов
np.random.seed(42)
arr3 = np.random.randint(10, size=(2, 3, 2))
shape_2_3 = np.arange(4, 10).reshape(2, 3)
shape_2 = np.array([6, 7])
print(arr3.shape)
print(shape_2_3.shape)
print(shape_2.shape)
arr3 == shape_2_3.reshape(2, 3, 1)
print(shape_2 < 6)
print(np.all(shape_2 < 6))
np.any(shape_2 < 6)

(2, 3, 2)
(2, 3)
(2,)
[False False]
False


np.False_

In [32]:
# скалярное произведение векторов
np.random.seed(42)
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 3, 4, 5, 6])
matrix1 = np.random.randint(10, size=[3, 3])
matrix2 = np.random.randint(10, size=[3, 3])
# vector2.shape = [-1, 1]
# vector2
np.dot(vector1, vector2)
vector1 @ vector2
np.inner(vector1, vector2)
#Внешнее произведение векторов
np.outer(vector1, vector2)

array([[ 2,  3,  4,  5,  6],
       [ 4,  6,  8, 10, 12],
       [ 6,  9, 12, 15, 18],
       [ 8, 12, 16, 20, 24],
       [10, 15, 20, 25, 30]])

In [45]:
#умножение матриц
vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 3, 4, 5])
mat = np.random.randint(10, size=[4, 3])
print(matrix1)
print(matrix2)
np.dot(matrix1, matrix2)
matrix1 @ matrix2
np.matmul(matrix1, matrix2)

[[6 3 7]
 [4 6 9]
 [2 6 7]]
[[4 3 7]
 [7 2 5]
 [4 1 7]]


array([[ 73,  31, 106],
       [ 94,  33, 121],
       [ 78,  25,  93]], dtype=int32)

In [50]:
# Матрица на вектор
print(vec2)
print(mat)

print(np.dot(vec2, mat))
print(mat @ vec1)
print(mat @ vec1[:np.newaxis])

[2 3 4 5]
[[3 7 6]
 [8 7 4]
 [1 4 7]
 [9 8 8]]
[79 91 92]
[35 34 30 49]
[35 34 30 49]


In [53]:
# элементы линейной алгебры
np.linalg.matrix_rank(mat) # ранг матрицы
np.linalg.inv(mat[:3]) # обратная матрица
np.trace(mat)  # cлед матрицы. Сумма на главной диагонали
np.linalg.det(mat[:3]) # определитель матрицы
np.linalg.eig(mat[:3]) # собственые значения и собственные вектора матрицы
np.linalg.svd(mat) # сингулярное разложение


SVDResult(U=array([[-0.43498795,  0.37009464,  0.74427615,  0.34622024],
       [-0.50845573, -0.53874782,  0.25903678, -0.61977698],
       [-0.32507567,  0.73319081, -0.31994954, -0.50437023],
       [-0.66826945, -0.18764855, -0.52591374,  0.49154726]]), S=array([21.52189346,  5.56737458,  1.95254765]), Vh=array([[-0.54419517, -0.61567836, -0.56990506],
       [-0.7463742 ,  0.04508456,  0.66399769],
       [-0.38311509,  0.78670677, -0.48406124]]))